/**
 * Global Semantic Error Codes
 * These codes are used by the frontend and backend for precise error handling.
 */
export enum ErrorCode {
  // Authentication Errors (401)
  ERR_AUTH_REQUIRED = 'ERR_AUTH_REQUIRED',
  ERR_AUTH_EXPIRED = 'ERR_AUTH_EXPIRED',
  ERR_INVALID_CREDENTIALS = 'ERR_INVALID_CREDENTIALS',

  // Authorization Errors (403)
  ERR_FORBIDDEN = 'ERR_FORBIDDEN',
  ERR_INSUFFICIENT_PERMISSIONS = 'ERR_INSUFFICIENT_PERMISSIONS',

  // Resource Errors (404/409)
  ERR_NOT_FOUND = 'ERR_NOT_FOUND',
  ERR_RESOURCE_EXISTS = 'ERR_RESOURCE_EXISTS',

  // Validation/Input Errors (400)
  ERR_BAD_REQUEST = 'ERR_BAD_REQUEST',
  ERR_VALIDATION_FAILED = 'ERR_VALIDATION_FAILED',
  ERR_MISSING_PARAMETERS = 'ERR_MISSING_PARAMETERS',
  ERR_INVALID_FORMAT = 'ERR_INVALID_FORMAT',

  // Payment Errors (402)
  ERR_PAYMENT_REQUIRED = 'ERR_PAYMENT_REQUIRED',
  ERR_INSUFFICIENT_FUNDS = 'ERR_INSUFFICIENT_FUNDS',
  
  // Transaction Errors (400/500)
  ERR_TRANSACTION_FAILED = 'ERR_TRANSACTION_FAILED',
  ERR_TRANSACTION_EXPIRED = 'ERR_TRANSACTION_EXPIRED',
  ERR_TRANSACTION_NOT_SIGNED = 'ERR_TRANSACTION_NOT_SIGNED',

  // Blockchain/Network Errors (503)
  ERR_BLOCKCHAIN_UNAVAILABLE = 'ERR_BLOCKCHAIN_UNAVAILABLE',
  ERR_NETWORK_ERROR = 'ERR_NETWORK_ERROR',
  ERR_WALLET_NOT_CONNECTED = 'ERR_WALLET_NOT_CONNECTED',
  ERR_WALLET_NOT_AVAILABLE = 'ERR_WALLET_NOT_AVAILABLE',

  // Database Errors (500)
  ERR_DATABASE_NOT_INITIALIZED = 'ERR_DATABASE_NOT_INITIALIZED',
  ERR_DATABASE_ERROR = 'ERR_DATABASE_ERROR',

  // Server/System Errors (500)
  ERR_INTERNAL_SERVER_ERROR = 'ERR_INTERNAL_SERVER_ERROR',
  ERR_NOT_IMPLEMENTED = 'ERR_NOT_IMPLEMENTED',
  ERR_MAX_RETRIES_EXCEEDED = 'ERR_MAX_RETRIES_EXCEEDED',
}

/**
 * Mapping of Error Codes to Standard HTTP Status Codes
 */
export const ErrorStatusMap: Record<ErrorCode, number> = {
  [ErrorCode.ERR_AUTH_REQUIRED]: 401,
  [ErrorCode.ERR_AUTH_EXPIRED]: 401,
  [ErrorCode.ERR_INVALID_CREDENTIALS]: 401,
  [ErrorCode.ERR_FORBIDDEN]: 403,
  [ErrorCode.ERR_INSUFFICIENT_PERMISSIONS]: 403,
  [ErrorCode.ERR_NOT_FOUND]: 404,
  [ErrorCode.ERR_RESOURCE_EXISTS]: 409,
  [ErrorCode.ERR_BAD_REQUEST]: 400,
  [ErrorCode.ERR_VALIDATION_FAILED]: 400,
  [ErrorCode.ERR_MISSING_PARAMETERS]: 400,
  [ErrorCode.ERR_INVALID_FORMAT]: 400,
  [ErrorCode.ERR_PAYMENT_REQUIRED]: 402,
  [ErrorCode.ERR_INSUFFICIENT_FUNDS]: 402,
  [ErrorCode.ERR_TRANSACTION_FAILED]: 400,
  [ErrorCode.ERR_TRANSACTION_EXPIRED]: 410,
  [ErrorCode.ERR_TRANSACTION_NOT_SIGNED]: 400,
  [ErrorCode.ERR_BLOCKCHAIN_UNAVAILABLE]: 503,
  [ErrorCode.ERR_NETWORK_ERROR]: 503,
  [ErrorCode.ERR_WALLET_NOT_CONNECTED]: 400,
  [ErrorCode.ERR_WALLET_NOT_AVAILABLE]: 400,
  [ErrorCode.ERR_DATABASE_NOT_INITIALIZED]: 500,
  [ErrorCode.ERR_DATABASE_ERROR]: 500,
  [ErrorCode.ERR_INTERNAL_SERVER_ERROR]: 500,
  [ErrorCode.ERR_NOT_IMPLEMENTED]: 501,
  [ErrorCode.ERR_MAX_RETRIES_EXCEEDED]: 503,
};
